### Write a Python script to collect 10 cat facts (each ≤ 80 characters) from the public API https://catfact.ninja/fact. Store them with unique IDs (fact1, fact2, ...) in a dictionary, then convert the data into a pandas DataFrame with two columns: id and facts, and display both.

In [27]:
import requests as rd
facts={}
lst1=[]
lst2=[]
facts_dir={}
data_pnt=1
while data_pnt<=10:
    v1=rd.get("https://catfact.ninja/fact")
    data=v1.json()
    if(data['length']<=80):
        facts[f"fact{data_pnt}"]=data['fact']
        data_pnt+=1
    else:
        pass
    
for keys,values in facts.items():
    lst1.append(keys)
    lst2.append(facts[keys])
facts_dir['id']=lst1
facts_dir['facts']=lst2
print(facts_dir)

{'id': ['fact1', 'fact2', 'fact3', 'fact4', 'fact5', 'fact6', 'fact7', 'fact8', 'fact9', 'fact10'], 'facts': ['A female cat is called a queen or a molly.', "Cats' hearing is much more sensitive than humans and dogs.", 'Cats have 300 million neurons; dogs have about 160 million', 'Cats have supersonic hearing', 'All cats have claws, and all except the cheetah sheath them when at rest.', 'Cats walk on their toes.', 'A queen (female cat) can begin mating when she is between 5 and 9 months old.', 'A group of cats is called a “clowder.”', 'A form of AIDS exists in cats.', 'In multi-cat households, cats of the opposite sex usually get along better.']}

# we should add this into tabular format
-> to print the data in table 
   use pandas
-> data will be in formatat of dictionary value list {'a':"[2,3,4]...}

so we should convert data int o romat

In [33]:
import pandas as pd
pd.DataFrame(facts_dir)

       id                                              facts
0   fact1         A female cat is called a queen or a molly.
1   fact2  Cats' hearing is much more sensitive than huma...
2   fact3  Cats have 300 million neurons; dogs have about...
3   fact4                       Cats have supersonic hearing
4   fact5  All cats have claws, and all except the cheeta...
5   fact6                           Cats walk on their toes.
6   fact7  A queen (female cat) can begin mating when she...
7   fact8             A group of cats is called a “clowder.”
8   fact9                     A form of AIDS exists in cats.
9  fact10  In multi-cat households, cats of the opposite ...

In [ ]:

# crating a database using random user api ,strree name,email ,username,pass ,ph number

In [96]:
import pandas as pd
import requests as rq
database={'name':[],'gender':[],'country':[],'state':[],'city':[], 'Streetname':[],'Email':[],'username':[],'password':[],'phone':[]}
for i in range(1,11):
    temp=rq.get('https://randomuser.me/api/')
    var=temp.json()
    person = {
        'name': var['results'][0]['name']['first'] + " " + var['results'][0]['name']['last'],
        'gender': var['results'][0]['gender'],
        'country': var['results'][0]['location']['country'],
        'state': var['results'][0]['location']['state'],
        'city': var['results'][0]['location']['city'],
        'Streetname': var['results'][0]['location']['street']['name'],
        'Email': var['results'][0]['email'],
        'username': var['results'][0]['login']['username'],
        'password': var['results'][0]['login']['password'],
        'phone': var['results'][0]['phone']
    }
    for every in database:
        database[every].append(person[every])

pd.DataFrame(database)

,name,gender,country,state,city,Streetname,Email,username,password,phone
0,Jan-Peter Niermann,male,Germany,Thüringen,Putbus,Kirchplatz,jan-peter.niermann@example.com,smallpeacock325,moscow,0460-3112224
1,Leopold Kratzer,male,Germany,Berlin,Hausach,Raiffeisenstraße,leopold.kratzer@example.com,greenbear328,stuart,0467-7757865
2,Nadežda Bakić,female,Serbia,South Bačka,Topola,Javorova,nadezda.bakic@example.com,tinyelephant749,78945612,010-0946-403
3,Kasper Rasmussen,male,Denmark,Syddanmark,Bælum,Sjællandsgade,kasper.rasmussen@example.com,crazytiger546,mark1,41875908
4,Yasmin Harte,female,Netherlands,Noord-Brabant,Oldekerk,Binnen,yasmin.harte@example.com,brownsnake734,marissa,(020) 7107408
5,Sebastian Larsen,male,Denmark,Syddanmark,Askeby,Bygmarken,sebastian.larsen@example.com,saddog340,lifetime,63996663
6,Miriam Gutiérrez,female,Spain,Melilla,Alicante,Calle de Pedro Bosch,miriam.gutierrez@example.com,happygoose954,odyssey,992-556-702
7,Jadranka Glavaš,female,Serbia,Pomoravlje,Batočina,Boranjska,jadranka.glavas@example.com,sadbutterfly887,teddy1,032-0701-606
8,Rafael Marchand,male,France,Yonne,Rueil-Malmaison,Avenue de l'Abbé-Roussel,rafael.marchand@example.com,crazymouse279,killjoy,05-36-75-04-64
9,Eetu Koivisto,male,Finland,North Karelia,Pomarkku,Pirkankatu,eetu.koivisto@example.com,yellowzebra253,theboss,05-491-648

In [4]:
help(dict.clear)

Help on method_descriptor:

clear(...) unbound builtins.dict method
    D.clear() -> None.  Remove all items from D.

In [8]:

print(type()

<class 'tuple'>