# Pivort table

### It allows you to transform long datasets into a structured format by grouping values and applying aggregation functions.

In [2]:
import os
import pandas as pd
import numpy as np

In [40]:
churn=pd.read_csv(r"C:\Users\chidv\Downloads\Data_sets\TelecomCustomerChurn2.csv")

churn

,customerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No,DSL,No,...,No,No,No,No,Monthly,Yes,Manual,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Manual,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Monthly,Yes,Manual,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Monthly,Yes,Manual,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Manual,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No,DSL,Yes,...,No,No,No,No,Monthly,Yes,Manual,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Monthly,Yes,Manual,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [42]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   Gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   Tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [39]:
car_df.pivot_table(index='make',values='price',aggfunc='mean',margins=True, margins_name="Grand mean")

                      price
make
alfa-romero    15498.333333
audi           17859.166667
bmw            26118.750000
chevrolet       6007.000000
dodge           7875.444444
honda           8184.692308
isuzu           8916.500000
jaguar         34600.000000
mazda          10652.882353
mercedes-benz  33647.000000
mercury        16503.000000
mitsubishi      9239.769231
nissan         10415.666667
peugot         15489.090909
plymouth        7963.428571
porsche        31400.500000
renault         9595.000000
saab           15223.333333
subaru          8541.250000
toyota          9885.812500
volkswagen     10077.500000
volvo          18063.181818
Grand mean     13207.129353

In [66]:
#loading the superstore dataset
Store_df=pd.read_excel(r"C:\Users\chidv\Downloads\Data_sets\Superstore.xlsx")
Store_df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

# Questions on the pivot table

In [75]:
#Count of orders by Shipping modes
Store_df.pivot_table(index='Ship Mode',values='Order ID',aggfunc='count')

                Order ID
Ship Mode
First Class         1538
Same Day             543
Second Class        1945
Standard Class      5968

In [81]:
#Average discount by Product category & Sub-category

Store_df.pivot_table(index=['Category','Sub-Category'],values='Discount',aggfunc='mean')

                              Discount
Category        Sub-Category
Furniture       Bookcases     0.211140
                Chairs        0.170178
                Furnishings   0.138349
                Tables        0.261285
Office Supplies Appliances    0.166524
                Art           0.074874
                Binders       0.372292
                Envelopes     0.080315
                Fasteners     0.082028
                Labels        0.068681
                Paper         0.074891
                Storage       0.074704
                Supplies      0.076842
Technology      Accessories   0.078452
                Copiers       0.161765
                Machines      0.306087
                Phones        0.154556

In [92]:
#Sales by Customer segment

Store_df.pivot_table(index=['Segment'],values='Sales',aggfunc='sum')

                    Sales
Segment
Consumer     1.161401e+06
Corporate    7.061464e+05
Home Office  4.296531e+05

In [110]:
#Sold products by Category & Sub-category

Store_df.pivot_table(index=['Category', 'Sub-Category'],values=['Product ID'],aggfunc='count')

                              Product ID
Category        Sub-Category
Furniture       Bookcases            228
                Chairs               617
                Furnishings          957
                Tables               319
Office Supplies Appliances           466
                Art                  796
                Binders             1523
                Envelopes            254
                Fasteners            217
                Labels               364
                Paper               1370
                Storage              846
                Supplies             190
Technology      Accessories          775
                Copiers               68
                Machines             115
                Phones               889

In [113]:
#Qty sold by Customer State and Product Category

Store_df.pivot_table(index=['State','Category'],values=['Quantity'],aggfunc='sum')

                               Quantity
State         Category
Alabama       Furniture              54
              Office Supplies       149
              Technology             53
Arizona       Furniture             188
              Office Supplies       501
...                                 ...
West Virginia Office Supplies        15
Wisconsin     Furniture             144
              Office Supplies       215
              Technology            104
Wyoming       Furniture               4

[142 rows x 1 columns]

In [114]:
#How does the average discount vary across different shipping modes and customer segments?

Store_df.pivot_table(index=['Ship Mode','Segment'],values=['Discount'],aggfunc='mean')

                            Discount
Ship Mode      Segment
First Class    Consumer     0.161131
               Corporate    0.171381
               Home Office  0.162465
Same Day       Consumer     0.159779
               Corporate    0.143860
               Home Office  0.140179
Second Class   Consumer     0.142314
               Corporate    0.138079
               Home Office  0.129430
Standard Class Consumer     0.162460
               Corporate    0.162384
               Home Office  0.149010

In [153]:
#What are the top 5 most profitable cities in each region?

sub_tab=Store_df.pivot_table(index=['Region','City'],values=['Profit'],aggfunc='sum')
top5=sub_tab.groupby(level=0, group_keys=False).apply(lambda x:x.sort_values('Profit', ascending=False).head(5))
top5

                             Profit
Region  City
Central Detroit          13181.7908
        Lafayette         8976.0973
        Minneapolis       6824.5846
        Jackson           5525.1992
        Springfield       3905.5891
East    New York City    62036.9837
        Newark            5793.7588
        Providence        5505.6569
        Columbia          3775.2237
        Lakewood          3190.0654
South   Atlanta           6993.6629
        Springfield       4568.5789
        Henderson         4518.8169
        Arlington         4424.0855
        Columbus          4104.1219
West    Los Angeles      30440.7579
        Seattle          29156.0967
        San Francisco    17507.3854
        San Diego         6377.1960
        North Las Vegas   2247.6899

🔹 level=0

Your index is a MultiIndex (['Region', 'City']).

level=0 means group by the first level of the index, i.e. Region.

So we’re grouping cities within each Region.

If we had written level=1, it would group by City instead (not useful here).

🔹 group_keys=False

By default, when you use .apply(), pandas adds the group key (Region name) to the result, which creates extra index nesting.

group_keys=False prevents pandas from inserting that extra level.

It keeps the output nicely formatted as Region, City → Profit.

In [118]:
#Profit by Region & Category for each quarter

Store_df.pivot_table(index=['Region','Category'],values=['Profit'],aggfunc='sum')

                             Profit
Region  Category
Central Furniture        -2871.0494
        Office Supplies   8879.9799
        Technology       33697.4320
East    Furniture         3046.1658
        Office Supplies  41014.5791
        Technology       47462.0351
South   Furniture         6771.2061
        Office Supplies  19986.3928
        Technology       19991.8314
West    Furniture        11504.9503
        Office Supplies  52609.8490
        Technology       44303.6496

In [ ]:
#find the top 2 quarters with highest profit

Store_df.pivot_table(index=[' '],values=['Profit'],aggfunc='sum')