In [1]:
import pandas as pd

In [3]:
x=pd.Series([52,2,6,1,65,8,4])
x

0    52
1     2
2     6
3     1
4    65
5     8
6     4
dtype: int64

In [5]:
len(x)

7

# Adding the series

In [7]:
S1=pd.Series([1,2,3,4])
S2=pd.Series([7,8])

In [9]:
S1

0    1
1    2
2    3
3    4
dtype: int64

In [10]:
S2

0    7
1    8
dtype: int64

In [16]:
S3=S1+S2
S3

0     8.0
1    10.0
2     NaN
3     NaN
dtype: float64

- S1+S2 #based on index it will adds the values

In [17]:
S3.size

4

In [19]:
pd.DataFrame([[1,2,3,4],[5,6,7,8]])

   0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [21]:
pd.DataFrame([[1,2,3,4],[5,6,7,8]])

   0  1  2  3
0  1  2  3  4
1  5  6  7  8